cache:
    untracked: true
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - cache/bundler/

before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --without test --path=cache/bundler --jobs $(nproc)

# update_staging:
#   only:
#     - staging
#   tags:
#     - ruby
#     - ruby2
#   script:
#     - bundle exec cap staging deploy

update_production:
  only:
    - master
  tags:
    - ruby
    - ruby2
  script:
    - bundle exec cap production deploy
