= Guardian of Times

Guardian of Times is a Rails Application to track times of teams.

== Developer Setup
* install docker, docker-compose, ruby
* start the postgres database through docker-compose: `docker-compose up`
* when running for the first time:
** install the gems: `bundle install`
*** if `pg` can't be installed, install the pg native libraries:
**** Arch: `pacman -S postgresql-libs`
** create the database layout: `rails db:migrate`
** generate a seed as described in <<seed, Generating a seed>>
* start rails: `rails s`

You can flash the database by removing the docker volume:
[source, bash]
----
$ docker container stop time-tracker_postgres_1
$ docker container rm time-tracker_postgres_1
$ docker volume rm time-tracker_time_tracker_db
----

[seed]
== Generating a seed
To generate a seed, we need your user informations in the `settings.yml` file.
Please append it as follows:
[source, yaml]
----
seed:
  email: <THM-Email>
  username: <THM-Userkennung>
  realname: <Your full name>
----

Then execute `rails db:seed`.

== Export
The export uses wkhtmltopdf (https://wkhtmltopdf.org).
It should be included as a binary gem using bundler.
If this fails, install wkhtmltopdf using your distribution and tell wicked_pdf (https://github.com/mileszs/wicked_pdf)  where the local installation is.
Tell bundler to install without the binary by running `bundle install --without wk_binary`.
