user:
  maximum_sign_ins_redirected_to_edit: 5
tag:
  name:
    length_minimum: 2
  description:
    length_minimum: 5

team:
  name:
    length_minimum: 5
  description:
    length_minimum: 5

  member:
    target_hours:
      minimum: 0
