name: Guardian of Times
repo_url: https://github.com/LiScI-Lab/Guardian-of-Times
commit_url: https://github.com/LiScI-Lab/Guardian-of-Times/commit/

user:
  maximum_sign_ins_redirected_to_edit: 5
  discard:
    disabled: false
    randomize_personal_data: true
    destroy_identities: true
    hand_over_teams: true


tag:
  name:
    length_minimum: 2
  description:
    length_minimum: 5

team:
  name:
    length_minimum: 5
  description:
    length_minimum: 5

  member:
    target_hours:
      minimum: 0

  progress:
    minimum_duration_for_import: 60